text = "Python is Easy"
print("Original String:", text)
# upper()
print("Uppercase:", text.upper())
# lower()
print("Lowercase:", text.lower())
# split()
words = text.split()
print("After split():", words)
# join()
joined_text = "-".join(words)
print("After join():", joined_text)
# replace()
new_text = text.replace("Easy", "Powerful")
print("After replace():", new_text)
